### ISSUE TITLE
[Issue]StockAero - Nodes

### ISSUE THREAD

**Issue by Kerbinator-CN** [JadeOfMaar/KipardSkylon#4]
IDK why you added so many nodes onto your ship.
I know that may be contributing to a good fixed installation
but if you want to use some other parts (wings or canard) things can become extraordinarily bad
because *Recently I've been in Bradley Whistance's discord for a while and I talked in depth with a friend who masters stock aero quite well in QQ chat*, he told me that **drag of parts are seriously affected by open nodes which dont have installations on them.** So why you need that nosecone is probably to shield off these nodes thus drug.
So consider making these nodes optional or removal to reduce the problem of node occlusion in stock aero (most high-performance-in-stock aircrafts utilizes that)

**Comment by JadeOfMaar** [comment]
Sorry, dude. Your friend has a spot on their certificate of mastery. Such nodes don't add drag. They provide an opportunity to subtract drag by putting something (pointy) there. Those odd nodes that I added **are required** to reduce drag because of the odd and unstoppable, **unfamiliar drag behavior** that these parts have. Without them, that drag would still be there. I troubleshoot this mod to Hell to learn that, and I've also learned from a master of stock aero.

The RAPIER itself would have to be designed as a pointy engine to reduce drag on its own.
